name: Tic Tac Toe

on:
  issues:
    types: [opened]

permissions:
  contents: write
  issues: write

jobs:
  update-tic-tac-toe:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'tttm#')
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Play Tic Tac Toe
        uses: athul/tic-tac-toe-readme@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
